apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - master-data-api-deployment.yaml
  - master-data-api-service.yaml
  - master-data-api-configmap.yaml

namespace: default

labels:
  managed-by: argocd
