{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgresql.name }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.env.POSTGRES_PASSWORD | quote }}
{{- end }}
