{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgresql.name }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.targetPort }}
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Values.postgresql.name }}
{{- end }}
