{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.name }}-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgresql.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
