apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telethai-dev

bases:
  - ../../base

namePrefix: dev-
nameSuffix: ""

replicas:
- name: telethai-master-data-api
  count: 1

images:
- name: telethai-master-data-api
  newTag: dev-latest

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: dev-telethai-master-data-api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 128Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 250m

configMapGenerator:
- name: telethai-master-data-api-config
  behavior: replace
  literals:
  - log-level=debug
  - database-pool-size=5
  - request-timeout=60000

commonLabels:
  environment: dev
