apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telehealth.fullname" . }}-config
  labels:
    {{- include "telehealth.labels" . | nindent 4 }}
data:
  log.level: {{ .Values.config.logLevel | quote }}
  api.environment: {{ .Values.config.environment | quote }}
  api.timeout: {{ .Values.config.apiTimeout | quote }}
