apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telethai

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: telethai-master-data-api
    newName: telethai-master-data-api
    newTag: latest

commonLabels:
  app: telethai-master-data-api
  version: v1
