apiVersion: v1
kind: ConfigMap
metadata:
  name: master-data-api-config
  namespace: default
  labels:
    app: telethai-master-data-api
data:
  log.level: "INFO"
  api.environment: "development"
  api.timeout: "30"
